import type { PhoneModel } from '@/types'
import { v4 as uuid } from 'uuid'

export function generateModels(): PhoneModel[] {
  const m = (brand: string, model: string, chipset?: string, frpMethod?: PhoneModel['frpMethod'], year?: number): PhoneModel => ({
    id: uuid(), brand, model, chipset, frpMethod, year,
  })

  return [
    // === SAMSUNG ===
    m('Samsung', 'Galaxy S25 Ultra', 'Snapdragon 8 Elite', 'Bypass', 2025),
    m('Samsung', 'Galaxy S25+', 'Snapdragon 8 Elite', 'Bypass', 2025),
    m('Samsung', 'Galaxy S25', 'Snapdragon 8 Elite', 'Bypass', 2025),
    m('Samsung', 'Galaxy S24 Ultra', 'Snapdragon 8 Gen 3', 'Bypass', 2024),
    m('Samsung', 'Galaxy S24+', 'Exynos 2400', 'Bypass', 2024),
    m('Samsung', 'Galaxy S24', 'Exynos 2400', 'Bypass', 2024),
    m('Samsung', 'Galaxy S23 Ultra', 'Snapdragon 8 Gen 2', 'Testpoint', 2023),
    m('Samsung', 'Galaxy S23+', 'Snapdragon 8 Gen 2', 'Testpoint', 2023),
    m('Samsung', 'Galaxy S23', 'Snapdragon 8 Gen 2', 'Testpoint', 2023),
    m('Samsung', 'Galaxy S22 Ultra', 'Snapdragon 8 Gen 1', 'Testpoint', 2022),
    m('Samsung', 'Galaxy S22+', 'Snapdragon 8 Gen 1', 'Testpoint', 2022),
    m('Samsung', 'Galaxy S22', 'Snapdragon 8 Gen 1', 'Testpoint', 2022),
    m('Samsung', 'Galaxy S21 Ultra', 'Exynos 2100', 'Testpoint', 2021),
    m('Samsung', 'Galaxy S21+', 'Exynos 2100', 'Testpoint', 2021),
    m('Samsung', 'Galaxy S21', 'Exynos 2100', 'Testpoint', 2021),
    m('Samsung', 'Galaxy S20 Ultra', 'Exynos 990', 'Testpoint', 2020),
    m('Samsung', 'Galaxy S20+', 'Exynos 990', 'Testpoint', 2020),
    m('Samsung', 'Galaxy S20', 'Exynos 990', 'Testpoint', 2020),
    m('Samsung', 'Galaxy S20 FE', 'Snapdragon 865', 'Testpoint', 2020),
    m('Samsung', 'Galaxy S10', 'Exynos 9820', 'Testpoint', 2019),
    m('Samsung', 'Galaxy S10+', 'Exynos 9820', 'Testpoint', 2019),
    m('Samsung', 'Galaxy S10e', 'Exynos 9820', 'Testpoint', 2019),
    m('Samsung', 'Galaxy S9', 'Exynos 9810', 'Testpoint', 2018),
    m('Samsung', 'Galaxy S9+', 'Exynos 9810', 'Testpoint', 2018),
    m('Samsung', 'Galaxy S8', 'Exynos 8895', 'Testpoint', 2017),
    m('Samsung', 'Galaxy S8+', 'Exynos 8895', 'Testpoint', 2017),
    m('Samsung', 'Galaxy A55', 'Exynos 1480', 'Bypass', 2024),
    m('Samsung', 'Galaxy A54', 'Exynos 1380', 'Bypass', 2023),
    m('Samsung', 'Galaxy A53', 'Exynos 1280', 'Testpoint', 2022),
    m('Samsung', 'Galaxy A52', 'Snapdragon 720G', 'Testpoint', 2021),
    m('Samsung', 'Galaxy A35', 'Exynos 1380', 'Bypass', 2024),
    m('Samsung', 'Galaxy A34', 'MediaTek Dimensity 1080', 'Bypass', 2023),
    m('Samsung', 'Galaxy A25', 'Exynos 1280', 'Bypass', 2024),
    m('Samsung', 'Galaxy A24', 'MediaTek Helio G99', 'Bypass', 2023),
    m('Samsung', 'Galaxy A15', 'MediaTek Helio G99', 'Bypass', 2024),
    m('Samsung', 'Galaxy A14', 'MediaTek Helio G80', 'Bypass', 2023),
    m('Samsung', 'Galaxy A13', 'Exynos 850', 'Bypass', 2022),
    m('Samsung', 'Galaxy A12', 'MediaTek Helio P35', 'SPD', 2021),
    m('Samsung', 'Galaxy A11', 'Snapdragon 450', 'Testpoint', 2020),
    m('Samsung', 'Galaxy A10', 'Exynos 7884', 'Testpoint', 2019),
    m('Samsung', 'Galaxy A04', 'MediaTek Helio G37', 'SPD', 2022),
    m('Samsung', 'Galaxy A03', 'Unisoc SC9863A', 'SPD', 2022),
    m('Samsung', 'Galaxy A02', 'MediaTek MT6739', 'SPD', 2021),
    m('Samsung', 'Galaxy Z Fold 6', 'Snapdragon 8 Gen 3', 'Bypass', 2024),
    m('Samsung', 'Galaxy Z Fold 5', 'Snapdragon 8 Gen 2', 'Bypass', 2023),
    m('Samsung', 'Galaxy Z Flip 5', 'Snapdragon 8 Gen 2', 'Bypass', 2023),
    m('Samsung', 'Galaxy Z Flip 4', 'Snapdragon 8+ Gen 1', 'Bypass', 2022),
    m('Samsung', 'Galaxy Z Flip 3', 'Snapdragon 888', 'Testpoint', 2021),
    m('Samsung', 'Galaxy Note 20 Ultra', 'Exynos 990', 'Testpoint', 2020),
    m('Samsung', 'Galaxy Note 20', 'Exynos 990', 'Testpoint', 2020),
    m('Samsung', 'Galaxy Note 10+', 'Exynos 9825', 'Testpoint', 2019),
    m('Samsung', 'Galaxy Note 10', 'Exynos 9825', 'Testpoint', 2019),
    m('Samsung', 'Galaxy J7', 'Exynos 7870', 'Testpoint', 2016),
    m('Samsung', 'Galaxy J6', 'Exynos 7870', 'Testpoint', 2018),
    m('Samsung', 'Galaxy J5', 'Snapdragon 410', 'Testpoint', 2015),
    m('Samsung', 'Galaxy M14', 'Exynos 1330', 'Bypass', 2023),
    m('Samsung', 'Galaxy M13', 'Exynos 850', 'Bypass', 2022),
    m('Samsung', 'Galaxy M12', 'Exynos 850', 'SPD', 2021),

    // === APPLE ===
    m('Apple', 'iPhone 17', 'Apple A19', 'Bypass', 2025),
    m('Apple', 'iPhone 16', 'Apple A18', 'Bypass', 2024),
    m('Apple', 'iPhone 16 Pro', 'Apple A18 Pro', 'Bypass', 2024),
    m('Apple', 'iPhone 16 Pro Max', 'Apple A18 Pro', 'Bypass', 2024),
    m('Apple', 'iPhone 15', 'Apple A16', 'Bypass', 2023),
    m('Apple', 'iPhone 15 Pro', 'Apple A17 Pro', 'Bypass', 2023),
    m('Apple', 'iPhone 15 Pro Max', 'Apple A17 Pro', 'Bypass', 2023),
    m('Apple', 'iPhone 14', 'Apple A15', 'Bypass', 2022),
    m('Apple', 'iPhone 14 Pro', 'Apple A16', 'Bypass', 2022),
    m('Apple', 'iPhone 14 Pro Max', 'Apple A16', 'Bypass', 2022),
    m('Apple', 'iPhone 13', 'Apple A15', 'Bypass', 2021),
    m('Apple', 'iPhone 13 Pro', 'Apple A15', 'Bypass', 2021),
    m('Apple', 'iPhone 13 Pro Max', 'Apple A15', 'Bypass', 2021),
    m('Apple', 'iPhone 12', 'Apple A14', 'Bypass', 2020),
    m('Apple', 'iPhone 12 Pro', 'Apple A14', 'Bypass', 2020),
    m('Apple', 'iPhone 12 Pro Max', 'Apple A14', 'Bypass', 2020),
    m('Apple', 'iPhone 11', 'Apple A13', 'Bypass', 2019),
    m('Apple', 'iPhone 11 Pro', 'Apple A13', 'Bypass', 2019),
    m('Apple', 'iPhone 11 Pro Max', 'Apple A13', 'Bypass', 2019),
    m('Apple', 'iPhone XR', 'Apple A12', 'Bypass', 2018),
    m('Apple', 'iPhone XS', 'Apple A12', 'Bypass', 2018),
    m('Apple', 'iPhone XS Max', 'Apple A12', 'Bypass', 2018),
    m('Apple', 'iPhone X', 'Apple A11', 'Bypass', 2017),
    m('Apple', 'iPhone 8', 'Apple A11', 'Bypass', 2017),
    m('Apple', 'iPhone 8 Plus', 'Apple A11', 'Bypass', 2017),
    m('Apple', 'iPhone 7', 'Apple A10', 'Bypass', 2016),
    m('Apple', 'iPhone 7 Plus', 'Apple A10', 'Bypass', 2016),
    m('Apple', 'iPhone SE (2nd gen)', 'Apple A13', 'Bypass', 2020),
    m('Apple', 'iPhone SE (3rd gen)', 'Apple A15', 'Bypass', 2022),

    // === XIAOMI ===
    m('Xiaomi', 'Xiaomi 14', 'Snapdragon 8 Gen 3', 'BROM', 2024),
    m('Xiaomi', 'Xiaomi 14 Ultra', 'Snapdragon 8 Gen 3', 'BROM', 2024),
    m('Xiaomi', 'Xiaomi 13', 'Snapdragon 8 Gen 2', 'BROM', 2023),
    m('Xiaomi', 'Xiaomi 13 Pro', 'Snapdragon 8 Gen 2', 'BROM', 2023),
    m('Xiaomi', 'Xiaomi 13 Lite', 'Snapdragon 7 Gen 1', 'BROM', 2023),
    m('Xiaomi', 'Xiaomi 12', 'Snapdragon 8 Gen 1', 'BROM', 2022),
    m('Xiaomi', 'Xiaomi 12 Pro', 'Snapdragon 8 Gen 1', 'BROM', 2022),
    m('Xiaomi', 'Xiaomi 11', 'Snapdragon 888', 'BROM', 2021),
    m('Xiaomi', 'Mi 10', 'Snapdragon 865', 'BROM', 2020),
    m('Xiaomi', 'Mi 10T', 'Snapdragon 865', 'BROM', 2020),
    m('Xiaomi', 'Mi 11', 'Snapdragon 888', 'BROM', 2021),
    m('Xiaomi', 'Mi 11 Ultra', 'Snapdragon 888', 'BROM', 2021),
    m('Xiaomi', 'Redmi Note 13', 'MediaTek Helio G99', 'BROM', 2024),
    m('Xiaomi', 'Redmi Note 13 Pro', 'MediaTek Dimensity 7200', 'BROM', 2024),
    m('Xiaomi', 'Redmi Note 12', 'Snapdragon 4 Gen 1', 'BROM', 2023),
    m('Xiaomi', 'Redmi Note 12 Pro', 'MediaTek Dimensity 1080', 'BROM', 2023),
    m('Xiaomi', 'Redmi Note 11', 'Snapdragon 680', 'BROM', 2022),
    m('Xiaomi', 'Redmi Note 11 Pro', 'MediaTek Helio G96', 'BROM', 2022),
    m('Xiaomi', 'Redmi Note 10', 'Snapdragon 678', 'BROM', 2021),
    m('Xiaomi', 'Redmi Note 10 Pro', 'Snapdragon 732G', 'BROM', 2021),
    m('Xiaomi', 'Redmi Note 9', 'MediaTek Helio G85', 'BROM', 2020),
    m('Xiaomi', 'Redmi 9', 'MediaTek Helio G80', 'BROM', 2020),
    m('Xiaomi', 'Redmi 10', 'MediaTek Helio G88', 'BROM', 2021),
    m('Xiaomi', 'Redmi 12', 'MediaTek Helio G88', 'BROM', 2023),
    m('Xiaomi', 'Redmi 13C', 'MediaTek Helio G85', 'BROM', 2023),
    m('Xiaomi', 'Redmi 9A', 'MediaTek Helio G25', 'BROM', 2020),
    m('POCO', 'POCO X6 Pro', 'MediaTek Dimensity 8300', 'BROM', 2024),
    m('POCO', 'POCO X5 Pro', 'Snapdragon 778G', 'BROM', 2023),
    m('POCO', 'POCO X4 Pro', 'Snapdragon 695', 'BROM', 2022),
    m('POCO', 'POCO F5', 'Snapdragon 7+ Gen 2', 'BROM', 2023),
    m('POCO', 'POCO F4', 'Snapdragon 870', 'BROM', 2022),
    m('POCO', 'POCO F3', 'Snapdragon 870', 'BROM', 2021),
    m('POCO', 'POCO M5', 'MediaTek Helio G99', 'BROM', 2022),
    m('POCO', 'POCO M4 Pro', 'MediaTek Helio G96', 'BROM', 2022),
    m('POCO', 'POCO C55', 'MediaTek Helio G85', 'BROM', 2023),
    m('POCO', 'POCO C40', 'Unisoc T606', 'SPD', 2022),

    // === HUAWEI ===
    m('Huawei', 'P60 Pro', 'Snapdragon 8+ Gen 1 4G', 'BROM', 2023),
    m('Huawei', 'P50 Pro', 'Snapdragon 888 4G', 'BROM', 2021),
    m('Huawei', 'P40 Pro', 'Kirin 990 5G', 'BROM', 2020),
    m('Huawei', 'P40', 'Kirin 990 5G', 'BROM', 2020),
    m('Huawei', 'P30 Pro', 'Kirin 980', 'BROM', 2019),
    m('Huawei', 'P30', 'Kirin 980', 'BROM', 2019),
    m('Huawei', 'Mate 50 Pro', 'Snapdragon 8+ Gen 1 4G', 'BROM', 2022),
    m('Huawei', 'Mate 40 Pro', 'Kirin 9000', 'BROM', 2020),
    m('Huawei', 'Mate 30 Pro', 'Kirin 990', 'BROM', 2019),
    m('Huawei', 'Nova 9', 'Snapdragon 778G 4G', 'BROM', 2021),
    m('Huawei', 'Nova 8', 'Kirin 985', 'BROM', 2020),
    m('Huawei', 'Honor 90', 'Snapdragon 7 Gen 1', 'BROM', 2023),
    m('Huawei', 'Honor 70', 'Snapdragon 778G+', 'BROM', 2022),
    m('Huawei', 'Honor 50', 'Snapdragon 778G', 'BROM', 2021),

    // === TECNO ===
    m('Tecno', 'Camon 30 Premier', 'MediaTek Dimensity 8200', 'SPD', 2024),
    m('Tecno', 'Camon 30 Pro', 'MediaTek Dimensity 8200', 'SPD', 2024),
    m('Tecno', 'Camon 30', 'MediaTek Helio G99', 'SPD', 2024),
    m('Tecno', 'Camon 20 Premier', 'MediaTek Dimensity 9000', 'SPD', 2023),
    m('Tecno', 'Camon 20 Pro', 'MediaTek Helio G99', 'SPD', 2023),
    m('Tecno', 'Camon 20', 'MediaTek Helio G85', 'SPD', 2023),
    m('Tecno', 'Camon 19 Pro', 'MediaTek Helio G96', 'SPD', 2022),
    m('Tecno', 'Camon 19', 'MediaTek Helio G85', 'SPD', 2022),
    m('Tecno', 'Camon 18', 'MediaTek Helio G88', 'SPD', 2021),
    m('Tecno', 'Spark 20 Pro', 'MediaTek Helio G99', 'SPD', 2024),
    m('Tecno', 'Spark 20', 'MediaTek Helio G85', 'SPD', 2024),
    m('Tecno', 'Spark 10 Pro', 'MediaTek Helio G88', 'SPD', 2023),
    m('Tecno', 'Spark 10', 'Unisoc T606', 'SPD', 2023),
    m('Tecno', 'Spark 9 Pro', 'MediaTek Helio G85', 'SPD', 2022),
    m('Tecno', 'Spark 9', 'MediaTek Helio G37', 'SPD', 2022),
    m('Tecno', 'Spark Go 1', 'Unisoc T603', 'SPD', 2024),
    m('Tecno', 'Spark Go 2024', 'Unisoc T603', 'SPD', 2024),
    m('Tecno', 'Spark Go 2023', 'Unisoc T606', 'SPD', 2023),
    m('Tecno', 'Spark Go 2022', 'Unisoc SC9863A', 'SPD', 2022),
    m('Tecno', 'Pova 6', 'MediaTek Dimensity 6080', 'SPD', 2024),
    m('Tecno', 'Pova 5', 'MediaTek Helio G99', 'SPD', 2023),
    m('Tecno', 'Pova 4', 'MediaTek Helio G99', 'SPD', 2022),
    m('Tecno', 'Pop 7', 'Unisoc T606', 'SPD', 2023),
    m('Tecno', 'Pop 6', 'Unisoc SC9863A', 'SPD', 2022),

    // === INFINIX ===
    m('Infinix', 'Hot 40 Pro', 'MediaTek Helio G99', 'SPD', 2024),
    m('Infinix', 'Hot 40', 'MediaTek Helio G88', 'SPD', 2024),
    m('Infinix', 'Hot 30', 'MediaTek Helio G88', 'SPD', 2023),
    m('Infinix', 'Hot 20', 'MediaTek Helio G85', 'SPD', 2022),
    m('Infinix', 'Hot 12', 'MediaTek Helio G85', 'SPD', 2022),
    m('Infinix', 'Hot 11', 'MediaTek Helio G70', 'SPD', 2021),
    m('Infinix', 'Hot 10', 'MediaTek Helio G70', 'SPD', 2020),
    m('Infinix', 'Note 40 Pro', 'MediaTek Helio G99', 'SPD', 2024),
    m('Infinix', 'Note 30', 'MediaTek Helio G99', 'SPD', 2023),
    m('Infinix', 'Note 12', 'MediaTek Helio G88', 'SPD', 2022),
    m('Infinix', 'Note 11', 'MediaTek Helio G96', 'SPD', 2021),
    m('Infinix', 'Note 10', 'MediaTek Helio G85', 'SPD', 2021),
    m('Infinix', 'Zero 30', 'MediaTek Dimensity 8020', 'SPD', 2023),
    m('Infinix', 'Zero 20', 'MediaTek Helio G99', 'SPD', 2022),
    m('Infinix', 'Zero X Pro', 'MediaTek Helio G95', 'SPD', 2021),
    m('Infinix', 'Smart 8', 'Unisoc T606', 'SPD', 2023),
    m('Infinix', 'Smart 7', 'Unisoc SC9863A', 'SPD', 2022),
    m('Infinix', 'Smart 6', 'Unisoc SC9863A', 'SPD', 2021),

    // === MOTOROLA ===
    m('Motorola', 'Moto G84', 'Snapdragon 695', 'Testpoint', 2023),
    m('Motorola', 'Moto G73', 'MediaTek Dimensity 930', 'BROM', 2023),
    m('Motorola', 'Moto G54', 'MediaTek Dimensity 7020', 'BROM', 2023),
    m('Motorola', 'Moto G53', 'Snapdragon 480+', 'Testpoint', 2023),
    m('Motorola', 'Moto G52', 'Snapdragon 680', 'Testpoint', 2022),
    m('Motorola', 'Moto G42', 'Snapdragon 680', 'Testpoint', 2022),
    m('Motorola', 'Moto G32', 'Snapdragon 680', 'Testpoint', 2022),
    m('Motorola', 'Moto G22', 'MediaTek Helio G37', 'SPD', 2022),
    m('Motorola', 'Moto G71', 'Snapdragon 695', 'Testpoint', 2022),
    m('Motorola', 'Moto G41', 'MediaTek Helio G85', 'BROM', 2022),
    m('Motorola', 'Moto G31', 'MediaTek Helio G85', 'BROM', 2022),
    m('Motorola', 'Moto G100', 'Snapdragon 870', 'Testpoint', 2021),
    m('Motorola', 'Moto G60', 'Snapdragon 732G', 'Testpoint', 2021),
    m('Motorola', 'Moto G50', 'Snapdragon 480', 'Testpoint', 2021),
    m('Motorola', 'Moto G30', 'Snapdragon 662', 'Testpoint', 2021),
    m('Motorola', 'Moto G9 Plus', 'Snapdragon 730G', 'Testpoint', 2020),
    m('Motorola', 'Moto G8 Power', 'Snapdragon 665', 'Testpoint', 2020),
    m('Motorola', 'Moto E40', 'Unisoc T606', 'SPD', 2021),
    m('Motorola', 'Moto E32', 'MediaTek Helio G37', 'SPD', 2022),
    m('Motorola', 'Moto E22', 'MediaTek Helio G37', 'SPD', 2022),
    m('Motorola', 'Moto Edge 50 Pro', 'Snapdragon 7 Gen 3', 'Testpoint', 2024),
    m('Motorola', 'Moto Edge 40', 'MediaTek Dimensity 8020', 'BROM', 2023),
    m('Motorola', 'Moto Edge 30', 'Snapdragon 778G+', 'Testpoint', 2022),
    m('Motorola', 'Moto Edge 20', 'Snapdragon 778G', 'Testpoint', 2021),

    // === LG ===
    m('LG', 'LG K62', 'MediaTek Helio P35', 'BROM', 2020),
    m('LG', 'LG K52', 'MediaTek Helio P35', 'BROM', 2020),
    m('LG', 'LG K42', 'MediaTek Helio P22', 'BROM', 2020),
    m('LG', 'LG K71', 'MediaTek Helio P35', 'BROM', 2020),
    m('LG', 'LG K41S', 'MediaTek Helio P22', 'BROM', 2020),
    m('LG', 'LG K51S', 'MediaTek Helio P35', 'BROM', 2020),
    m('LG', 'LG K22', 'Qualcomm QM215', 'Testpoint', 2020),
    m('LG', 'LG K31', 'MediaTek Helio P22', 'BROM', 2020),
    m('LG', 'LG Velvet', 'Snapdragon 765G', 'Testpoint', 2020),
    m('LG', 'LG Wing', 'Snapdragon 765G', 'Testpoint', 2020),
    m('LG', 'LG V60 ThinQ', 'Snapdragon 865', 'Testpoint', 2020),
    m('LG', 'LG G8 ThinQ', 'Snapdragon 855', 'Testpoint', 2019),
    m('LG', 'LG G7 ThinQ', 'Snapdragon 845', 'Testpoint', 2018),

    // === GOOGLE ===
    m('Google', 'Pixel 8 Pro', 'Google Tensor G3', 'Bypass', 2023),
    m('Google', 'Pixel 8', 'Google Tensor G3', 'Bypass', 2023),
    m('Google', 'Pixel 7 Pro', 'Google Tensor G2', 'Bypass', 2022),
    m('Google', 'Pixel 7', 'Google Tensor G2', 'Bypass', 2022),
    m('Google', 'Pixel 7a', 'Google Tensor G2', 'Bypass', 2023),
    m('Google', 'Pixel 6 Pro', 'Google Tensor', 'Bypass', 2021),
    m('Google', 'Pixel 6', 'Google Tensor', 'Bypass', 2021),
    m('Google', 'Pixel 6a', 'Google Tensor', 'Bypass', 2022),
    m('Google', 'Pixel 5', 'Snapdragon 765G', 'Testpoint', 2020),
    m('Google', 'Pixel 4a', 'Snapdragon 730G', 'Testpoint', 2020),
    m('Google', 'Pixel 4', 'Snapdragon 855', 'Testpoint', 2019),

    // === ALCATEL ===
    m('Alcatel', 'Alcatel 1 (2021)', 'MediaTek MT6739', 'SPD', 2021),
    m('Alcatel', 'Alcatel 1B (2022)', 'Unisoc SC9863A', 'SPD', 2022),
    m('Alcatel', 'Alcatel 1V', 'Unisoc SC9863A', 'SPD', 2020),
    m('Alcatel', 'Alcatel 3L', 'MediaTek Helio A25', 'BROM', 2021),
    m('Alcatel', 'Alcatel 3X', 'MediaTek Helio P23', 'BROM', 2020),

    // === ZTE ===
    m('ZTE', 'ZTE Blade A73', 'Unisoc T606', 'SPD', 2023),
    m('ZTE', 'ZTE Blade A53', 'Unisoc SC9863A', 'SPD', 2022),
    m('ZTE', 'ZTE Blade A33', 'Unisoc SC9863A', 'SPD', 2022),
    m('ZTE', 'ZTE Nubia Focus', 'MediaTek Helio G99', 'BROM', 2024),
    m('ZTE', 'ZTE Nubia Neo', 'Unisoc T820', 'SPD', 2023),

    // === SAMSUNG - Venezuela comunes ===
    m('Samsung', 'Galaxy A01', 'Snapdragon 439', 'SPD', 2020),
    m('Samsung', 'Galaxy A05', 'MediaTek Helio G85', 'BROM', 2023),
    m('Samsung', 'Galaxy A06', 'MediaTek Helio G85', 'BROM', 2024),
    m('Samsung', 'Galaxy A10s', 'Exynos 7884B', 'Testpoint', 2019),
    m('Samsung', 'Galaxy A20', 'Exynos 7884', 'Testpoint', 2019),
    m('Samsung', 'Galaxy A20e', 'Exynos 7884B', 'Testpoint', 2019),
    m('Samsung', 'Galaxy A21', 'MediaTek Helio P35', 'SPD', 2020),
    m('Samsung', 'Galaxy A21s', 'Exynos 850', 'SPD', 2020),
    m('Samsung', 'Galaxy A22', 'MediaTek Dimensity 700', 'BROM', 2021),
    m('Samsung', 'Galaxy A23', 'Snapdragon 680', 'Testpoint', 2022),
    m('Samsung', 'Galaxy A30', 'Exynos 7904', 'Testpoint', 2019),
    m('Samsung', 'Galaxy A30s', 'Exynos 7904', 'Testpoint', 2019),
    m('Samsung', 'Galaxy A31', 'MediaTek Helio P65', 'BROM', 2020),
    m('Samsung', 'Galaxy A32', 'MediaTek Dimensity 720', 'BROM', 2021),
    m('Samsung', 'Galaxy A33', 'Exynos 1280', 'Testpoint', 2022),
    m('Samsung', 'Galaxy A50', 'Exynos 9610', 'Testpoint', 2019),
    m('Samsung', 'Galaxy A51', 'Exynos 9611', 'Testpoint', 2019),
    m('Samsung', 'Galaxy A70', 'Snapdragon 675', 'Testpoint', 2019),
    m('Samsung', 'Galaxy A71', 'Snapdragon 730', 'Testpoint', 2020),
    m('Samsung', 'Galaxy A72', 'Snapdragon 720G', 'Testpoint', 2021),
    m('Samsung', 'Galaxy A73', 'Snapdragon 778G', 'Testpoint', 2022),
    m('Samsung', 'Galaxy J2', 'Spreadtrum SC8830', 'SPD', 2016),
    m('Samsung', 'Galaxy J4', 'Exynos 7570', 'Testpoint', 2018),
    m('Samsung', 'Galaxy J4+', 'Snapdragon 425', 'Testpoint', 2018),
    m('Samsung', 'Galaxy J6+', 'Snapdragon 425', 'Testpoint', 2018),
    m('Samsung', 'Galaxy J7+', 'MediaTek Helio P20', 'BROM', 2017),
    m('Samsung', 'Galaxy J8', 'Snapdragon 450', 'Testpoint', 2018),
    m('Samsung', 'Galaxy J8+', 'Snapdragon 450', 'Testpoint', 2018),
    m('Samsung', 'Galaxy M15', 'MediaTek Dimensity 6100+', 'BROM', 2024),
    m('Samsung', 'Galaxy M21', 'Exynos 9611', 'Testpoint', 2020),
    m('Samsung', 'Galaxy M31', 'Exynos 9611', 'Testpoint', 2020),
    m('Samsung', 'Galaxy M32', 'MediaTek Helio G80', 'BROM', 2021),
    m('Samsung', 'Galaxy M51', 'Snapdragon 730G', 'Testpoint', 2020),
    m('Samsung', 'Galaxy M52', 'Snapdragon 778G', 'Testpoint', 2021),
    m('Samsung', 'Galaxy M53', 'MediaTek Dimensity 900', 'BROM', 2022),
    m('Samsung', 'Galaxy M54', 'Exynos 1380', 'Bypass', 2023),
    m('Samsung', 'Galaxy M55', 'Snapdragon 7 Gen 1', 'Bypass', 2024),
    m('Samsung', 'Galaxy F12', 'Exynos 850', 'SPD', 2021),
    m('Samsung', 'Galaxy F13', 'Exynos 850', 'SPD', 2022),
    m('Samsung', 'Galaxy F14', 'Exynos 1330', 'Bypass', 2023),
    m('Samsung', 'Galaxy F22', 'MediaTek Helio G80', 'BROM', 2021),
    m('Samsung', 'Galaxy F23', 'Snapdragon 750G', 'Testpoint', 2022),
    m('Samsung', 'Galaxy A05s', 'Snapdragon 680', 'Testpoint', 2023),
    m('Samsung', 'Galaxy A03s', 'MediaTek Helio P35', 'SPD', 2021),
    m('Samsung', 'Galaxy A03 Core', 'Unisoc SC9863A', 'SPD', 2021),
    m('Samsung', 'Galaxy S7 Edge', 'Exynos 8890', 'Testpoint', 2016),

    // === TECNO - Venezuela comunes ===
    m('Tecno', 'Spark 4', 'MediaTek Helio A22', 'SPD', 2019),
    m('Tecno', 'Spark 5', 'MediaTek Helio A22', 'SPD', 2020),
    m('Tecno', 'Spark 5 Pro', 'MediaTek Helio A25', 'SPD', 2020),
    m('Tecno', 'Spark 6', 'MediaTek Helio G70', 'SPD', 2020),
    m('Tecno', 'Spark 6 Air', 'MediaTek Helio A22', 'SPD', 2020),
    m('Tecno', 'Spark 7', 'MediaTek Helio G70', 'SPD', 2021),
    m('Tecno', 'Spark 7T', 'MediaTek Helio G70', 'SPD', 2021),
    m('Tecno', 'Spark 8', 'MediaTek Helio G25', 'SPD', 2021),
    m('Tecno', 'Spark 8C', 'Unisoc T606', 'SPD', 2022),
    m('Tecno', 'Spark 8P', 'MediaTek Helio G70', 'SPD', 2021),
    m('Tecno', 'Camon 12', 'MediaTek Helio P22', 'SPD', 2019),
    m('Tecno', 'Camon 12 Air', 'MediaTek Helio A22', 'SPD', 2019),
    m('Tecno', 'Camon 15', 'MediaTek Helio P22', 'SPD', 2020),
    m('Tecno', 'Camon 15 Air', 'MediaTek Helio A22', 'SPD', 2020),
    m('Tecno', 'Camon 16', 'MediaTek Helio G70', 'SPD', 2020),
    m('Tecno', 'Camon 16 Pro', 'MediaTek Helio G70', 'SPD', 2020),
    m('Tecno', 'Camon 16 S', 'MediaTek Helio G70', 'SPD', 2020),
    m('Tecno', 'Camon 17', 'MediaTek Helio G70', 'SPD', 2021),
    m('Tecno', 'Camon 17 Pro', 'MediaTek Helio G70', 'SPD', 2021),
    m('Tecno', 'Camon 17P', 'MediaTek Helio G70', 'SPD', 2021),
    m('Tecno', 'Pova', 'MediaTek Helio G80', 'SPD', 2020),
    m('Tecno', 'Pova 2', 'MediaTek Helio G85', 'SPD', 2021),
    m('Tecno', 'Pova 3', 'MediaTek Helio G88', 'SPD', 2022),
    m('Tecno', 'Spark Go 2020', 'Unisoc SC9832E', 'SPD', 2020),
    m('Tecno', 'Spark Go 2021', 'Unisoc SC9863A', 'SPD', 2021),

    // === INFINIX - Venezuela comunes ===
    m('Infinix', 'Hot 8', 'MediaTek Helio P22', 'BROM', 2019),
    m('Infinix', 'Hot 9', 'MediaTek Helio A25', 'BROM', 2020),
    m('Infinix', 'Hot 9 Play', 'MediaTek Helio A25', 'BROM', 2020),
    m('Infinix', 'Hot 10 Lite', 'MediaTek Helio A25', 'BROM', 2020),
    m('Infinix', 'Hot 11S', 'MediaTek Helio G88', 'SPD', 2021),
    m('Infinix', 'Hot 20i', 'MediaTek Helio G25', 'BROM', 2022),
    m('Infinix', 'Hot 20S', 'MediaTek Helio G96', 'SPD', 2022),
    m('Infinix', 'Hot 30i', 'MediaTek Helio G37', 'BROM', 2023),
    m('Infinix', 'Note 7', 'MediaTek Helio G70', 'BROM', 2020),
    m('Infinix', 'Note 7 Lite', 'MediaTek Helio G70', 'BROM', 2020),
    m('Infinix', 'Note 8', 'MediaTek Helio G80', 'BROM', 2020),
    m('Infinix', 'Note 8i', 'MediaTek Helio G80', 'BROM', 2020),
    m('Infinix', 'Smart 5', 'Unisoc SC9863A', 'SPD', 2020),
    m('Infinix', 'Smart 5 Pro', 'Unisoc T606', 'SPD', 2021),
    m('Infinix', 'Zero 5', 'MediaTek Helio P20', 'BROM', 2017),
    m('Infinix', 'Zero 6', 'MediaTek Helio P60', 'BROM', 2018),
    m('Infinix', 'Zero 8', 'MediaTek Helio G90T', 'BROM', 2020),
    m('Infinix', 'Zero X', 'MediaTek Helio G95', 'BROM', 2021),

    // === MOTOROLA - Venezuela comunes ===
    m('Motorola', 'Moto E4', 'Snapdragon 425', 'Testpoint', 2017),
    m('Motorola', 'Moto E5', 'Snapdragon 425', 'Testpoint', 2018),
    m('Motorola', 'Moto E5 Play', 'Snapdragon 425', 'Testpoint', 2018),
    m('Motorola', 'Moto E6', 'Snapdragon 435', 'Testpoint', 2019),
    m('Motorola', 'Moto E6 Play', 'MediaTek Helio P22', 'BROM', 2019),
    m('Motorola', 'Moto E7', 'Snapdragon 632', 'Testpoint', 2020),
    m('Motorola', 'Moto E7 Plus', 'Snapdragon 460', 'Testpoint', 2020),
    m('Motorola', 'Moto E13', 'Unisoc T606', 'SPD', 2023),
    m('Motorola', 'Moto E14', 'Unisoc T606', 'SPD', 2024),
    m('Motorola', 'Moto G4', 'Snapdragon 617', 'Testpoint', 2016),
    m('Motorola', 'Moto G5', 'Snapdragon 430', 'Testpoint', 2017),
    m('Motorola', 'Moto G5 Plus', 'Snapdragon 625', 'Testpoint', 2017),
    m('Motorola', 'Moto G6', 'Snapdragon 450', 'Testpoint', 2018),
    m('Motorola', 'Moto G6 Plus', 'Snapdragon 630', 'Testpoint', 2018),
    m('Motorola', 'Moto G7', 'Snapdragon 632', 'Testpoint', 2019),
    m('Motorola', 'Moto G7 Plus', 'Snapdragon 636', 'Testpoint', 2019),
    m('Motorola', 'Moto G7 Power', 'Snapdragon 632', 'Testpoint', 2019),
    m('Motorola', 'Moto G8', 'Snapdragon 665', 'Testpoint', 2019),
    m('Motorola', 'Moto G8 Plus', 'Snapdragon 665', 'Testpoint', 2019),
    m('Motorola', 'Moto G9', 'Snapdragon 662', 'Testpoint', 2020),
    m('Motorola', 'Moto G10', 'Snapdragon 460', 'Testpoint', 2021),
    m('Motorola', 'Moto G20', 'Unisoc T700', 'SPD', 2021),
    m('Motorola', 'Moto G51', 'Snapdragon 480+', 'Testpoint', 2021),
    m('Motorola', 'Moto Edge', 'Snapdragon 765G', 'Testpoint', 2020),
    m('Motorola', 'Moto Edge+', 'Snapdragon 865', 'Testpoint', 2020),

    // === XIAOMI - Venezuela comunes ===
    m('Xiaomi', 'Redmi 7', 'Snapdragon 632', 'BROM', 2019),
    m('Xiaomi', 'Redmi 8', 'Snapdragon 439', 'BROM', 2019),
    m('Xiaomi', 'Redmi 8A', 'Snapdragon 439', 'BROM', 2019),
    m('Xiaomi', 'Redmi 9C', 'MediaTek Helio G35', 'BROM', 2020),
    m('Xiaomi', 'Redmi 10A', 'MediaTek Helio G25', 'BROM', 2022),
    m('Xiaomi', 'Redmi 12C', 'MediaTek Helio G85', 'BROM', 2023),
    m('Xiaomi', 'Redmi Note 7', 'Snapdragon 660', 'BROM', 2019),
    m('Xiaomi', 'Redmi Note 8', 'Snapdragon 665', 'BROM', 2019),
    m('Xiaomi', 'Redmi Note 8 Pro', 'MediaTek Helio G90T', 'BROM', 2019),
    m('Xiaomi', 'Redmi Note 8T', 'Snapdragon 665', 'BROM', 2020),
    m('Xiaomi', 'Redmi Note 9S', 'Snapdragon 720G', 'BROM', 2020),
    m('Xiaomi', 'Redmi Note 9T', 'MediaTek Dimensity 800U', 'BROM', 2021),
    m('Xiaomi', 'Redmi Note 11S', 'MediaTek Helio G96', 'BROM', 2022),

    // === HUAWEI - Venezuela comunes ===
    m('Huawei', 'Y3 (2017)', 'MediaTek MT6737', 'BROM', 2017),
    m('Huawei', 'Y5 (2017)', 'MediaTek MT6737T', 'BROM', 2017),
    m('Huawei', 'Y5 (2018)', 'MediaTek MT6739', 'BROM', 2018),
    m('Huawei', 'Y5 Prime (2018)', 'Snapdragon 425', 'Testpoint', 2018),
    m('Huawei', 'Y6 (2017)', 'MediaTek MT6737T', 'BROM', 2017),
    m('Huawei', 'Y6 (2018)', 'Snapdragon 425', 'Testpoint', 2018),
    m('Huawei', 'Y6 Pro (2019)', 'MediaTek Helio A22', 'BROM', 2019),
    m('Huawei', 'Y7 (2018)', 'Snapdragon 430', 'Testpoint', 2018),
    m('Huawei', 'Y7 (2019)', 'Snapdragon 450', 'Testpoint', 2019),
    m('Huawei', 'Y7 Prime (2019)', 'Snapdragon 450', 'Testpoint', 2019),
    m('Huawei', 'Y9 (2018)', 'Kirin 710', 'BROM', 2018),
    m('Huawei', 'Y9 (2019)', 'Kirin 710F', 'BROM', 2019),
    m('Huawei', 'Y9 Prime (2019)', 'Kirin 710F', 'BROM', 2019),
    m('Huawei', 'Y9a', 'MediaTek Helio G80', 'BROM', 2020),
    m('Huawei', 'P Smart', 'Kirin 659', 'BROM', 2017),
    m('Huawei', 'P Smart+', 'Kirin 659', 'BROM', 2018),
    m('Huawei', 'P Smart 2019', 'Kirin 710', 'BROM', 2019),
    m('Huawei', 'P Smart Pro', 'Kirin 710F', 'BROM', 2019),
    m('Huawei', 'P Smart Z', 'Kirin 710F', 'BROM', 2019),
    m('Huawei', 'Honor 8S', 'MediaTek Helio A22', 'BROM', 2019),
    m('Huawei', 'Honor 8A', 'MediaTek Helio P35', 'BROM', 2019),
    m('Huawei', 'Honor 9S', 'MediaTek Helio A22', 'BROM', 2020),
    m('Huawei', 'Honor 9A', 'MediaTek Helio P22', 'BROM', 2020),
    m('Huawei', 'Honor 10 Lite', 'Kirin 710', 'BROM', 2018),
    m('Huawei', 'Honor 20 Lite', 'Kirin 710', 'BROM', 2019),

    // === LG - Venezuela comunes ===
    m('LG', 'LG K9', 'Snapdragon 210', 'Testpoint', 2018),
    m('LG', 'LG K10 (2017)', 'MediaTek MT6750', 'BROM', 2017),
    m('LG', 'LG K11', 'MediaTek MT6750', 'BROM', 2017),
    m('LG', 'LG K12+', 'MediaTek Helio P22', 'BROM', 2019),
    m('LG', 'LG K20 (2019)', 'MediaTek Helio P22', 'BROM', 2019),
    m('LG', 'LG K40', 'MediaTek Helio P22', 'BROM', 2019),
    m('LG', 'LG K50', 'MediaTek Helio P22', 'BROM', 2019),
    m('LG', 'LG K50S', 'MediaTek Helio P35', 'BROM', 2019),
    m('LG', 'LG K61', 'MediaTek Helio P35', 'BROM', 2020),
    m('LG', 'LG K8 (2017)', 'Snapdragon 425', 'Testpoint', 2017),
    m('LG', 'LG Q6', 'Snapdragon 435', 'Testpoint', 2017),
    m('LG', 'LG Q7', 'MediaTek MT6750', 'BROM', 2018),
    m('LG', 'LG Q60', 'MediaTek Helio P22', 'BROM', 2019),
    m('LG', 'LG Q70', 'Snapdragon 675', 'Testpoint', 2019),

    // === APPLE - missing models ===
    m('Apple', 'iPhone 6s', 'Apple A9', 'Bypass', 2015),
    m('Apple', 'iPhone 6s Plus', 'Apple A9', 'Bypass', 2015),
    m('Apple', 'iPhone 6', 'Apple A8', 'Bypass', 2014),
    m('Apple', 'iPhone 6 Plus', 'Apple A8', 'Bypass', 2014),
    m('Apple', 'iPhone 5s', 'Apple A7', 'Bypass', 2013),
    m('Apple', 'iPhone 5', 'Apple A6', 'Bypass', 2012),
    m('Apple', 'iPhone SE (1st gen)', 'Apple A9', 'Bypass', 2016),

    // === ADDITIONAL MODELS FROM PhoneSpecsAPI + CELL WORLD ===
    // 392 models added from PhoneSpecsAPI (Samsung, Apple, Xiaomi, Huawei, Google, Nokia)
    // and from CELL WORLD screen catalog (Tecno, Infinix, Motorola, LG, Alcatel, ZTE, BLU, Vivo, TCL, Blackview, Umidigi, Krip)

    // === SAMSUNG - PhoneSpecsAPI ===
    m('Samsung', 'Galaxy S7', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy S6 Edge+', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy S6 Edge', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy S6', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy S5', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy S4', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy S III', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy S II', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy S', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A54 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A34 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A24 4G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A14 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A04s', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A04e', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A13 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A23 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A33 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A53 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A73 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A12 Nacho', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A71 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A51 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A42 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A41', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A02s', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A01 Core', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A10e', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A20s', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A40', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A50s', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A60', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A70s', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A80', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A90 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A6 (2018)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A6+ (2018)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A7 (2018)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A8 (2018)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A8+ (2018)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A8 Star (2018)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A9 (2018)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A3 (2017)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A5 (2017)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A7 (2017)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A3 (2016)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A5 (2016)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A7 (2016)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A8 (2016)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A9 (2016)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy A9 Pro (2016)', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Z Flip', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Z Flip 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Z Flip 6', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Fold', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Z Fold 2', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Z Fold 3', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Z Fold 4', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Note', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Note II', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Note 3', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Note 4', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Note 5', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Note 8', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy Note 9', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy M10', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy M20', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy M30', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy M02', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy M33 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy M04', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy M14 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy M34 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy M54 5G', 'Exynos/Snapdragon', 'Testpoint'),
    m('Samsung', 'Galaxy M55 5G', 'Exynos/Snapdragon', 'Testpoint'),

    // === APPLE - PhoneSpecsAPI ===
    m('Apple', 'iPhone', 'Apple Silicon', 'Bypass'),
    m('Apple', 'iPhone 3G', 'Apple Silicon', 'Bypass'),
    m('Apple', 'iPhone 3GS', 'Apple Silicon', 'Bypass'),
    m('Apple', 'iPhone 4', 'Apple Silicon', 'Bypass'),
    m('Apple', 'iPhone 4S', 'Apple Silicon', 'Bypass'),
    m('Apple', 'iPhone 5C', 'Apple Silicon', 'Bypass'),
    m('Apple', 'iPhone SE (1st generation)', 'Apple Silicon', 'Bypass'),
    m('Apple', 'iPhone SE (2nd generation)', 'Apple Silicon', 'Bypass'),
    m('Apple', 'iPhone 12 mini', 'Apple Silicon', 'Bypass'),
    m('Apple', 'iPhone 17 Pro', 'Apple Silicon', 'Bypass'),
    m('Apple', 'iPhone 17 Pro Max', 'Apple Silicon', 'Bypass'),

    // === XIAOMI - PhoneSpecsAPI ===
    m('Xiaomi', 'Xiaomi 14 Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Xiaomi 13 Ultra', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Xiaomi 12T', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Xiaomi 12T Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Xiaomi 15', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Xiaomi 15 Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Xiaomi 15 Ultra', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Xiaomi 15S Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Xiaomi 15T', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Xiaomi 15T Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Xiaomi 17', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Xiaomi 17 Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Xiaomi 17 Pro Max', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Xiaomi 17 Ultra', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Mi 10 Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Mi 10 Ultra', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Mi 10T Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Mi 10i', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Mi 11 Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Mi 11 Lite', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Mi 11X', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Mi 11X Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Mi 10T Lite', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Mi 12X', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi K20', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi K20 Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi K40', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi K40 Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi K40 Pro+', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi K50', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi K50 Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi K50 Ultra', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi K70', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi K70 Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi K70 Ultra', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi Note 10S', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi Note 12T', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi Note 12 Pro Speed', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi Note 12S', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi Note 13 Pro+', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi Note 15', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi Note 15 5G', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi Note 15 Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi Note 15 Pro+', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi Note 15 Pro 4G', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'Redmi 9 Power', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'POCO F1', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'POCO F2 Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'POCO X7', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'POCO X7 Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'POCO F8 Pro', 'Snapdragon/MediaTek', 'BROM'),
    m('Xiaomi', 'POCO F8 Ultra', 'Snapdragon/MediaTek', 'BROM'),

    // === HUAWEI - PhoneSpecsAPI ===
    m('Huawei', 'P50', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'P40 Pro+', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'P20 Pro', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'P20', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'P10 Plus', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'P10', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'P9 Plus', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'P9', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'P8', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Mate 60 Pro', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Mate 60', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Mate 60 Pro+', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Mate 50', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Mate 40 Pro+', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Mate 30', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Mate 20 Pro', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Mate 20', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Mate 10 Pro', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Mate 10', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Mate 9', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Mate S', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Mate 7', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Pura 70', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Pura 70 Pro', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Pura 70 Ultra', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Nova 8i', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Honor 9X', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Honor 8C', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Honor Play', 'Kirin/Snapdragon', 'BROM'),
    m('Huawei', 'Honor Play 9A', 'Kirin/Snapdragon', 'BROM'),

    // === GOOGLE - PhoneSpecsAPI ===
    m('Google', 'Pixel 5a 5G', 'Tensor', 'Bypass'),
    m('Google', 'Pixel 4a 5G', 'Tensor', 'Bypass'),
    m('Google', 'Pixel 4 XL', 'Tensor', 'Bypass'),
    m('Google', 'Pixel 3a XL', 'Tensor', 'Bypass'),
    m('Google', 'Pixel 3a', 'Tensor', 'Bypass'),
    m('Google', 'Pixel 3 XL', 'Tensor', 'Bypass'),
    m('Google', 'Pixel 3', 'Tensor', 'Bypass'),
    m('Google', 'Pixel 2 XL', 'Tensor', 'Bypass'),
    m('Google', 'Pixel 2', 'Tensor', 'Bypass'),
    m('Google', 'Pixel XL', 'Tensor', 'Bypass'),
    m('Google', 'Pixel', 'Tensor', 'Bypass'),
    m('Google', 'Pixel 5a', 'Tensor', 'Bypass'),

    // === NOKIA - PhoneSpecsAPI ===
    m('Nokia', 'Nokia G42 5G', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia G310 5G', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia C12 Pro', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia X50', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia G60 5G', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia X30 5G', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia G21', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia G11', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia X10', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia C30', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia G20', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia G50', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia XR20', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 3.4', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 5.3', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 8.3 5G', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 2.3', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 7.2', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 4.2', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 9 PureView', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 6.1', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 8 Sirocco', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 7 Plus', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 8', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 6', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 5', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 3', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 3310 (2017)', 'Snapdragon', 'Testpoint'),
    m('Nokia', 'Nokia 3210 4G (2024)', 'Snapdragon', 'Testpoint'),

    // === EXTRA BRANDS - CELL WORLD / Venezuela comunes ===
    m('Tecno', 'Spark Go', 'Unisoc/MediaTek', 'SPD'),
    m('Tecno', 'Camon 18P', 'Unisoc/MediaTek', 'SPD'),
    m('Tecno', 'Camon 30S', 'Unisoc/MediaTek', 'SPD'),
    m('Tecno', 'Pop 1F', 'Unisoc/MediaTek', 'SPD'),
    m('Tecno', 'Pop 2F', 'Unisoc/MediaTek', 'SPD'),
    m('Infinix', 'Hot 10S', 'Unisoc/MediaTek', 'SPD'),
    m('Infinix', 'Hot 12i', 'Unisoc/MediaTek', 'SPD'),
    m('Infinix', 'Hot 20Wi', 'Unisoc/MediaTek', 'SPD'),
    m('Infinix', 'Hot 50i', 'Unisoc/MediaTek', 'SPD'),
    m('Infinix', 'Note 40', 'Unisoc/MediaTek', 'SPD'),
    m('Motorola', 'Moto E4 Plus', 'Snapdragon', 'Testpoint'),
    m('Motorola', 'Moto E5 Plus', 'Snapdragon', 'Testpoint'),
    m('Motorola', 'Moto E6 Plus', 'Snapdragon', 'Testpoint'),
    m('Motorola', 'Moto E6i', 'Snapdragon', 'Testpoint'),
    m('Motorola', 'Moto E6S', 'Snapdragon', 'Testpoint'),
    m('Motorola', 'Moto E7 Power', 'Snapdragon', 'Testpoint'),
    m('Motorola', 'Moto E22i', 'Snapdragon', 'Testpoint'),
    m('Motorola', 'Moto E30', 'Snapdragon', 'Testpoint'),
    m('Motorola', 'Moto G4 Plus', 'Snapdragon', 'Testpoint'),
    m('Motorola', 'Moto G9 Play', 'Snapdragon', 'Testpoint'),
    m('Motorola', 'Moto Edge Neo', 'Snapdragon', 'Testpoint'),
    m('Motorola', 'Moto Edge Lite', 'Snapdragon', 'Testpoint'),
    m('Motorola', 'Moto Edge Fusion', 'Snapdragon', 'Testpoint'),
    m('LG', 'K4 (2017)', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K8 (2017)', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K10 (2017)', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K11', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K12+', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K20 (2019)', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K22', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K31', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K40', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K40S', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K41S', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K42', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K50', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K50S', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K51S', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K52', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K61', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K62', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'K71', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'Q6', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'Q7', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'Q60', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'Q70', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'Q710', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'Stylo 4', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'Stylo 5', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'Stylo 6', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'Velvet', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'Wing', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'V60 ThinQ', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'G8 ThinQ', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'G7 ThinQ', 'MediaTek/Snapdragon', 'BROM'),
    m('LG', 'Stylo 4', 'MediaTek/Snapdragon', 'BROM'),
    m('Alcatel', '1B (2020)', 'Unisoc', 'SPD'),
    m('Alcatel', '1V (2019)', 'Unisoc', 'SPD'),
    m('Alcatel', '1V (2020)', 'Unisoc', 'SPD'),
    m('Alcatel', '1V (2021)', 'Unisoc', 'SPD'),
    m('Alcatel', '1X (2019)', 'Unisoc', 'SPD'),
    m('Alcatel', '1S (2019)', 'Unisoc', 'SPD'),
    m('Alcatel', '1S (2020)', 'Unisoc', 'SPD'),
    m('Alcatel', '1S (2021)', 'Unisoc', 'SPD'),
    m('Alcatel', '1SE (2020)', 'Unisoc', 'SPD'),
    m('Alcatel', '3C (2019)', 'Unisoc', 'SPD'),
    m('Alcatel', '3X (2018)', 'Unisoc', 'SPD'),
    m('Alcatel', '3X (2019)', 'Unisoc', 'SPD'),
    m('Alcatel', '3X (2020)', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A3', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A3 Lite', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A5', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A7', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A7S', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A31', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A31 Lite', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A33', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A34', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A35', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A35E', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A53', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A54', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A71', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A72', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade A73', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade L8', 'Unisoc', 'SPD'),
    m('ZTE', 'Blade L130', 'Unisoc', 'SPD'),
    m('ZTE', 'Nubia Focus', 'Unisoc', 'SPD'),
    m('ZTE', 'Nubia Focus 5G', 'Unisoc', 'SPD'),
    m('ZTE', 'Nubia Focus Pro', 'Unisoc', 'SPD'),
    m('ZTE', 'Nubia Neo', 'Unisoc', 'SPD'),
    m('ZTE', 'Nubia Neo 5G', 'Unisoc', 'SPD'),
    m('ZTE', 'Nubia Music', 'Unisoc', 'SPD'),
    m('BLU', 'G50 Plus', 'MediaTek', 'BROM'),
    m('BLU', 'G51 Plus', 'MediaTek', 'BROM'),
    m('BLU', 'G53', 'MediaTek', 'BROM'),
    m('BLU', 'G60', 'MediaTek', 'BROM'),
    m('BLU', 'G61 Plus', 'MediaTek', 'BROM'),
    m('BLU', 'G70', 'MediaTek', 'BROM'),
    m('BLU', 'G71 Plus', 'MediaTek', 'BROM'),
    m('BLU', 'G73', 'MediaTek', 'BROM'),
    m('BLU', 'G8', 'MediaTek', 'BROM'),
    m('BLU', 'G80', 'MediaTek', 'BROM'),
    m('BLU', 'G90', 'MediaTek', 'BROM'),
    m('BLU', 'G91 Pro', 'MediaTek', 'BROM'),
    m('BLU', 'G91S', 'MediaTek', 'BROM'),
    m('BLU', 'S91', 'MediaTek', 'BROM'),
    m('Vivo', 'Y11S', 'MediaTek', 'BROM'),
    m('Vivo', 'Y15S', 'MediaTek', 'BROM'),
    m('Vivo', 'Y16', 'MediaTek', 'BROM'),
    m('Vivo', 'Y17', 'MediaTek', 'BROM'),
    m('Vivo', 'Y20', 'MediaTek', 'BROM'),
    m('Vivo', 'Y20i', 'MediaTek', 'BROM'),
    m('Vivo', 'Y21', 'MediaTek', 'BROM'),
    m('Vivo', 'Y21S', 'MediaTek', 'BROM'),
    m('Vivo', 'Y22', 'MediaTek', 'BROM'),
    m('Vivo', 'Y30', 'MediaTek', 'BROM'),
    m('Vivo', 'Y33S', 'MediaTek', 'BROM'),
    m('Vivo', 'Y50', 'MediaTek', 'BROM'),
    m('Vivo', 'Y51', 'MediaTek', 'BROM'),
    m('Vivo', 'Y53S', 'MediaTek', 'BROM'),
    m('Vivo', 'Y71', 'MediaTek', 'BROM'),
    m('Vivo', 'Y83', 'MediaTek', 'BROM'),
    m('Vivo', 'Y85', 'MediaTek', 'BROM'),
    m('Vivo', 'Y93', 'MediaTek', 'BROM'),
    m('Vivo', 'X6', 'MediaTek', 'BROM'),
    m('Vivo', 'V70', 'MediaTek', 'BROM'),
    m('TCL', '10 SE', 'MediaTek', 'BROM'),
    m('TCL', '20 E', 'MediaTek', 'BROM'),
    m('TCL', '20 L', 'MediaTek', 'BROM'),
    m('TCL', '20 SE', 'MediaTek', 'BROM'),
    m('TCL', '30 SE', 'MediaTek', 'BROM'),
    m('TCL', '40 SE', 'MediaTek', 'BROM'),
    m('TCL', 'L10 Lite', 'MediaTek', 'BROM'),
    m('Blackview', 'A70', 'MediaTek', 'BROM'),
    m('Blackview', 'A80', 'MediaTek', 'BROM'),
    m('Blackview', 'A80 Plus', 'MediaTek', 'BROM'),
    m('Blackview', 'A90', 'MediaTek', 'BROM'),
    m('Blackview', 'A90 Plus', 'MediaTek', 'BROM'),
    m('Blackview', 'A100', 'MediaTek', 'BROM'),
    m('Blackview', 'BV5100', 'MediaTek', 'BROM'),
    m('Blackview', 'BV6600', 'MediaTek', 'BROM'),
    m('Umidigi', 'A5 Pro', 'MediaTek', 'BROM'),
    m('Umidigi', 'A7', 'MediaTek', 'BROM'),
    m('Umidigi', 'A7 Pro', 'MediaTek', 'BROM'),
    m('Umidigi', 'A9', 'MediaTek', 'BROM'),
    m('Umidigi', 'A9 Pro', 'MediaTek', 'BROM'),
    m('Umidigi', 'A11', 'MediaTek', 'BROM'),
    m('Umidigi', 'A11 Pro Max', 'MediaTek', 'BROM'),
    m('Umidigi', 'A11S', 'MediaTek', 'BROM'),
    m('Umidigi', 'Bison', 'MediaTek', 'BROM'),
    m('Umidigi', 'Bison GT', 'MediaTek', 'BROM'),
    m('Umidigi', 'Bison X10', 'MediaTek', 'BROM'),
    m('Umidigi', 'Bison X10 Pro', 'MediaTek', 'BROM'),
    m('Umidigi', 'Power', 'MediaTek', 'BROM'),
    m('Umidigi', 'Power 5', 'MediaTek', 'BROM'),
    m('Umidigi', 'Power 5S', 'MediaTek', 'BROM'),
    m('Krip', 'K55', 'MediaTek', 'BROM'),
    m('Krip', 'K57', 'MediaTek', 'BROM'),
    m('Krip', 'K5M', 'MediaTek', 'BROM'),
    m('Krip', 'K6', 'MediaTek', 'BROM'),
    m('Krip', 'K6B', 'MediaTek', 'BROM'),
    m('Krip', 'K68', 'MediaTek', 'BROM'),

    // === SAMSUNG - missing A series 5G & F series ===
    m('Samsung', 'Galaxy A22 5G', 'MediaTek Dimensity 700', 'BROM'),
    m('Samsung', 'Galaxy A32 5G', 'MediaTek Dimensity 720', 'BROM'),
    m('Samsung', 'Galaxy A52 5G', 'Snapdragon 750G', 'Testpoint'),
    m('Samsung', 'Galaxy A52s 5G', 'Snapdragon 778G', 'Testpoint'),
    m('Samsung', 'Galaxy A72 5G', 'Snapdragon 750G', 'Testpoint'),
    m('Samsung', 'Galaxy A82 5G', 'Snapdragon 855+', 'Testpoint'),
    m('Samsung', 'Galaxy F02s', 'Snapdragon 450', 'Testpoint'),
    m('Samsung', 'Galaxy F04', 'MediaTek Helio P35', 'SPD'),
    m('Samsung', 'Galaxy F05', 'MediaTek Helio G85', 'BROM'),
    m('Samsung', 'Galaxy F06', 'MediaTek Helio G85', 'BROM'),
    m('Samsung', 'Galaxy F12', 'Exynos 850', 'SPD'),
    m('Samsung', 'Galaxy F13', 'Exynos 850', 'SPD'),
    m('Samsung', 'Galaxy F14', 'Exynos 1330', 'Bypass'),
    m('Samsung', 'Galaxy F14 5G', 'Exynos 1330', 'Bypass'),
    m('Samsung', 'Galaxy F15', 'MediaTek Dimensity 6100+', 'BROM'),
    m('Samsung', 'Galaxy F22', 'MediaTek Helio G80', 'BROM'),
    m('Samsung', 'Galaxy F23', 'Snapdragon 750G', 'Testpoint'),
    m('Samsung', 'Galaxy F34', 'Exynos 1280', 'Testpoint'),
    m('Samsung', 'Galaxy F41', 'Exynos 9611', 'Testpoint'),
    m('Samsung', 'Galaxy F42 5G', 'MediaTek Dimensity 700', 'BROM'),
    m('Samsung', 'Galaxy F52 5G', 'Snapdragon 750G', 'Testpoint'),
    m('Samsung', 'Galaxy F54', 'Exynos 1380', 'Bypass'),
    m('Samsung', 'Galaxy F55', 'Snapdragon 7 Gen 1', 'Bypass'),
    m('Samsung', 'Galaxy F62', 'Exynos 9825', 'Testpoint'),
  ]
}
